version: '3.8'

services:
  playlist:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.playlist.rule=Host(`playlist.homelab`)'
      - 'traefik.http.services.playlist.loadbalancer.server.port=3000'
    env_file:
      - .env.local

networks:
  traefik_web:
    external: true