version: '3.8'

services:
  pdf-generator:
    build:
      context: ./pdf-generator
      dockerfile: Dockerfile
    restart: always

  playlist:
    build:
      context: ./main
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.playlist.rule=Host(`playlist.homelab`)'
      - 'traefik.http.services.playlist.loadbalancer.server.port=3000'
    env_file:
      - .env.local

networks:
  traefik_web:
    external: true